#!/usr/bin/env python3
"""Bridge storage/ -> web/data.js for the browser app.

Reads the normalized YAML tables and emits a single JavaScript file that
assigns `window.DATC_DATA`. A plain JS object (not fetched JSON) is used so the
app runs straight from the filesystem (file://) with no server or CORS setup.

Link fields (synonyms/variants/antagonists) are id FKs into the terms table;
they are resolved here to the target term's display name so the UI can render
them as clickable words. `concepts` ids resolve to concept display names.

Run `scripts/validate.py` first; this bridge assumes referential integrity.
"""
import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
TERMS = ROOT / "storage" / "terms"
CONCEPTS = ROOT / "storage" / "concepts"
OUT = ROOT / "web" / "data.js"


def display(slug: str) -> str:
    """attach -> Attach, linked-list -> Linked List."""
    return " ".join(part.capitalize() for part in slug.split("-"))


def load(directory):
    rows = {}
    for f in sorted(directory.glob("*.yml")):
        rows[f.stem] = yaml.safe_load(f.read_text(encoding="utf-8")) or {}
    return rows


def main():
    terms = load(TERMS)
    concepts = load(CONCEPTS)

    # id -> display name, per table
    term_name = {d["id"]: display(slug) for slug, d in terms.items()}
    concept_name = {d["id"]: display(slug) for slug, d in concepts.items()}

    # Concepts ordered by id (matches the design's fixed concept order).
    concept_list = [concept_name[i] for i in sorted(concept_name)]

    def resolve(ids, table):
        return [table[i] for i in (ids or []) if i in table]

    words = []
    for slug, d in sorted(terms.items(), key=lambda kv: display(kv[0])):
        t = d.get("type")
        words.append({
            "word": display(slug),
            "slug": slug,
            "type": t.capitalize() if t else "",
            "concepts": resolve(d.get("concepts"), concept_name),
            "variants": resolve(d.get("variants"), term_name),
            "synonyms": resolve(d.get("synonyms"), term_name),
            "antagonists": resolve(d.get("antagonists"), term_name),
        })

    payload = {"concepts": concept_list, "words": words}
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// GENERATED by scripts/build.py from storage/ — do not edit by hand.\n"
        "window.DATC_DATA = "
        + json.dumps(payload, ensure_ascii=False, indent=2)
        + ";\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT.relative_to(ROOT)}: {len(words)} words, {len(concept_list)} concepts")
    return 0


if __name__ == "__main__":
    sys.exit(main())
