// GENERATED by scripts/build.py from storage/ — do not edit by hand.
window.DATC_DATA = {
  "concepts": [
    "Hierarchy",
    "Lifecycle",
    "Signaling",
    "Partiality",
    "Connectivity",
    "Transformability",
    "Resource",
    "Assurance",
    "Access",
    "Disposition",
    "Traceability"
  ],
  "words": [
    {
      "word": "Accumulate",
      "slug": "accumulate",
      "type": "Verb",
      "concepts": [
        "Partiality"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Accusation",
      "slug": "accusation",
      "type": "Noun",
      "concepts": [
        "Assurance"
      ],
      "variants": [
        "Defender"
      ],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Act",
      "slug": "act",
      "type": "Verb",
      "concepts": [
        "Disposition"
      ],
      "variants": [
        "Actor"
      ],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Active",
      "slug": "active",
      "type": "Adjective",
      "concepts": [
        "Disposition"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Actor",
      "slug": "actor",
      "type": "Noun",
      "concepts": [
        "Disposition"
      ],
      "variants": [
        "Act"
      ],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Adapt",
      "slug": "adapt",
      "type": "Verb",
      "concepts": [
        "Transformability"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Admit",
      "slug": "admit",
      "type": "Verb",
      "concepts": [
        "Access"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Age",
      "slug": "age",
      "type": "Noun",
      "concepts": [
        "Lifecycle",
        "Hierarchy"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Aggregate",
      "slug": "aggregate",
      "type": "Verb",
      "concepts": [
        "Partiality"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Aggressive",
      "slug": "aggressive",
      "type": "Adjective",
      "concepts": [
        "Disposition"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Allege",
      "slug": "allege",
      "type": "Verb",
      "concepts": [
        "Assurance"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Arm",
      "slug": "arm",
      "type": "Verb",
      "concepts": [
        "Access"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Assert",
      "slug": "assert",
      "type": "Verb",
      "concepts": [
        "Assurance"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Attach",
      "slug": "attach",
      "type": "Verb",
      "concepts": [
        "Connectivity"
      ],
      "variants": [
        "Detach"
      ],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Blame",
      "slug": "blame",
      "type": "Verb",
      "concepts": [
        "Traceability"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Bleed",
      "slug": "bleed",
      "type": "Verb",
      "concepts": [
        "Resource"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Blocking",
      "slug": "blocking",
      "type": "Adjective",
      "concepts": [
        "Disposition"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Bound",
      "slug": "bound",
      "type": "Noun",
      "concepts": [
        "Assurance"
      ],
      "variants": [
        "Boundary"
      ],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Boundary",
      "slug": "boundary",
      "type": "Noun",
      "concepts": [
        "Assurance",
        "Access"
      ],
      "variants": [
        "Bound"
      ],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Branch",
      "slug": "branch",
      "type": "Noun",
      "concepts": [
        "Hierarchy"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Breach",
      "slug": "breach",
      "type": "Verb",
      "concepts": [
        "Assurance"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Bus",
      "slug": "bus",
      "type": "Noun",
      "concepts": [
        "Signaling",
        "Connectivity"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Call",
      "slug": "call",
      "type": "Verb",
      "concepts": [
        "Signaling",
        "Traceability"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Channels",
      "slug": "channels",
      "type": "Noun",
      "concepts": [
        "Signaling",
        "Connectivity"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Cheap",
      "slug": "cheap",
      "type": "Adjective",
      "concepts": [
        "Resource"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Child",
      "slug": "child",
      "type": "Noun",
      "concepts": [
        "Hierarchy"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Chunks",
      "slug": "chunks",
      "type": "Noun",
      "concepts": [
        "Partiality"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Claims",
      "slug": "claims",
      "type": "Noun",
      "concepts": [
        "Assurance"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Compound",
      "slug": "compound",
      "type": "Verb",
      "concepts": [
        "Partiality"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Consume",
      "slug": "consume",
      "type": "Verb",
      "concepts": [
        "Signaling",
        "Resource"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Contract",
      "slug": "contract",
      "type": "Noun",
      "concepts": [
        "Assurance"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Control",
      "slug": "control",
      "type": "Verb",
      "concepts": [
        "Access"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Convert",
      "slug": "convert",
      "type": "Verb",
      "concepts": [
        "Transformability"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Create",
      "slug": "create",
      "type": "Verb",
      "concepts": [
        "Lifecycle"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Decision",
      "slug": "decision",
      "type": "Noun",
      "concepts": [
        "Disposition"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Defender",
      "slug": "defender",
      "type": "Noun",
      "concepts": [
        "Assurance"
      ],
      "variants": [
        "Accusation"
      ],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Degree",
      "slug": "degree",
      "type": "Noun",
      "concepts": [
        "Disposition"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Demote",
      "slug": "demote",
      "type": "Verb",
      "concepts": [
        "Hierarchy"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Derivation",
      "slug": "derivation",
      "type": "Noun",
      "concepts": [
        "Transformability"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Destroy",
      "slug": "destroy",
      "type": "Verb",
      "concepts": [
        "Lifecycle"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Detach",
      "slug": "detach",
      "type": "Verb",
      "concepts": [
        "Connectivity"
      ],
      "variants": [
        "Attach"
      ],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Dilution",
      "slug": "dilution",
      "type": "Noun",
      "concepts": [
        "Resource"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Disable",
      "slug": "disable",
      "type": "Verb",
      "concepts": [
        "Access"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Disarm",
      "slug": "disarm",
      "type": "Verb",
      "concepts": [
        "Access"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Discriminate",
      "slug": "discriminate",
      "type": "Verb",
      "concepts": [
        "Partiality"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Disembark",
      "slug": "disembark",
      "type": "Verb",
      "concepts": [
        "Connectivity"
      ],
      "variants": [
        "Embark"
      ],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Dispatch",
      "slug": "dispatch",
      "type": "Verb",
      "concepts": [
        "Signaling"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Domestic",
      "slug": "domestic",
      "type": "Adjective",
      "concepts": [
        "Access"
      ],
      "variants": [
        "Foreign"
      ],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Downgrade",
      "slug": "downgrade",
      "type": "Verb",
      "concepts": [
        "Transformability"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Drain",
      "slug": "drain",
      "type": "Verb",
      "concepts": [
        "Resource"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Edition",
      "slug": "edition",
      "type": "Noun",
      "concepts": [
        "Transformability"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Embark",
      "slug": "embark",
      "type": "Verb",
      "concepts": [
        "Connectivity"
      ],
      "variants": [
        "Disembark"
      ],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Enable",
      "slug": "enable",
      "type": "Verb",
      "concepts": [
        "Access"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Enforce",
      "slug": "enforce",
      "type": "Verb",
      "concepts": [
        "Assurance"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Evacuate",
      "slug": "evacuate",
      "type": "Verb",
      "concepts": [
        "Resource"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Exclude",
      "slug": "exclude",
      "type": "Verb",
      "concepts": [
        "Access"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Exit",
      "slug": "exit",
      "type": "Verb",
      "concepts": [
        "Lifecycle"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Expensive",
      "slug": "expensive",
      "type": "Adjective",
      "concepts": [
        "Resource"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "External",
      "slug": "external",
      "type": "Adjective",
      "concepts": [
        "Access"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Feed",
      "slug": "feed",
      "type": "Verb",
      "concepts": [
        "Resource"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Fiber",
      "slug": "fiber",
      "type": "Noun",
      "concepts": [
        "Connectivity"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Foreign",
      "slug": "foreign",
      "type": "Adjective",
      "concepts": [
        "Access"
      ],
      "variants": [
        "Domestic"
      ],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Foreigner",
      "slug": "foreigner",
      "type": "Noun",
      "concepts": [
        "Access"
      ],
      "variants": [
        "Stranger"
      ],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Fork",
      "slug": "fork",
      "type": "Verb",
      "concepts": [
        "Lifecycle",
        "Hierarchy"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Guarantee",
      "slug": "guarantee",
      "type": "Verb",
      "concepts": [
        "Assurance"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Guard",
      "slug": "guard",
      "type": "Verb",
      "concepts": [
        "Assurance",
        "Access"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Hydration",
      "slug": "hydration",
      "type": "Noun",
      "concepts": [
        "Lifecycle"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Include",
      "slug": "include",
      "type": "Verb",
      "concepts": [
        "Access"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Internal",
      "slug": "internal",
      "type": "Adjective",
      "concepts": [
        "Access"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Interpreter",
      "slug": "interpreter",
      "type": "Noun",
      "concepts": [
        "Transformability"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Key",
      "slug": "key",
      "type": "Noun",
      "concepts": [
        "Access"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Leaf",
      "slug": "leaf",
      "type": "Noun",
      "concepts": [
        "Hierarchy"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Leak",
      "slug": "leak",
      "type": "Verb",
      "concepts": [
        "Resource"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Mediator",
      "slug": "mediator",
      "type": "Noun",
      "concepts": [
        "Signaling"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Message",
      "slug": "message",
      "type": "Noun",
      "concepts": [
        "Signaling"
      ],
      "variants": [
        "Messenger"
      ],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Messenger",
      "slug": "messenger",
      "type": "Noun",
      "concepts": [
        "Signaling"
      ],
      "variants": [
        "Message"
      ],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Module",
      "slug": "module",
      "type": "Noun",
      "concepts": [
        "Partiality"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Mount",
      "slug": "mount",
      "type": "Verb",
      "concepts": [
        "Connectivity",
        "Lifecycle"
      ],
      "variants": [
        "Unmount"
      ],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Oldest",
      "slug": "oldest",
      "type": "Adjective",
      "concepts": [
        "Hierarchy"
      ],
      "variants": [
        "Youngest"
      ],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Option",
      "slug": "option",
      "type": "Noun",
      "concepts": [
        "Disposition"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Orphan",
      "slug": "orphan",
      "type": "Noun",
      "concepts": [
        "Hierarchy",
        "Lifecycle"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Parent",
      "slug": "parent",
      "type": "Noun",
      "concepts": [
        "Hierarchy"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Partial",
      "slug": "partial",
      "type": "Adjective",
      "concepts": [
        "Partiality"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Passive",
      "slug": "passive",
      "type": "Adjective",
      "concepts": [
        "Disposition"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Pay",
      "slug": "pay",
      "type": "Verb",
      "concepts": [
        "Resource"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Penalty",
      "slug": "penalty",
      "type": "Noun",
      "concepts": [
        "Resource"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Pollution",
      "slug": "pollution",
      "type": "Noun",
      "concepts": [
        "Assurance"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Pool",
      "slug": "pool",
      "type": "Noun",
      "concepts": [
        "Resource"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Predecessor",
      "slug": "predecessor",
      "type": "Noun",
      "concepts": [
        "Hierarchy"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Prevent",
      "slug": "prevent",
      "type": "Verb",
      "concepts": [
        "Assurance"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Private",
      "slug": "private",
      "type": "Adjective",
      "concepts": [
        "Access"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Promote",
      "slug": "promote",
      "type": "Verb",
      "concepts": [
        "Hierarchy"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Proof",
      "slug": "proof",
      "type": "Noun",
      "concepts": [
        "Assurance"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Propose",
      "slug": "propose",
      "type": "Verb",
      "concepts": [
        "Signaling"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Protocol",
      "slug": "protocol",
      "type": "Noun",
      "concepts": [
        "Signaling"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Public",
      "slug": "public",
      "type": "Adjective",
      "concepts": [
        "Access"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Punish",
      "slug": "punish",
      "type": "Verb",
      "concepts": [
        "Assurance"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Puppet",
      "slug": "puppet",
      "type": "Noun",
      "concepts": [
        "Disposition"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Pursue",
      "slug": "pursue",
      "type": "Verb",
      "concepts": [
        "Assurance"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Rail",
      "slug": "rail",
      "type": "Noun",
      "concepts": [
        "Connectivity"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Receiver",
      "slug": "receiver",
      "type": "Noun",
      "concepts": [
        "Signaling"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Reduce",
      "slug": "reduce",
      "type": "Verb",
      "concepts": [
        "Partiality"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Rotten",
      "slug": "rotten",
      "type": "Adjective",
      "concepts": [
        "Lifecycle"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Safe",
      "slug": "safe",
      "type": "Adjective",
      "concepts": [
        "Assurance"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Sender",
      "slug": "sender",
      "type": "Noun",
      "concepts": [
        "Signaling"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Shards",
      "slug": "shards",
      "type": "Noun",
      "concepts": [
        "Partiality"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Sibling",
      "slug": "sibling",
      "type": "Noun",
      "concepts": [
        "Hierarchy"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Signal",
      "slug": "signal",
      "type": "Noun",
      "concepts": [
        "Signaling"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Spawn",
      "slug": "spawn",
      "type": "Verb",
      "concepts": [
        "Lifecycle"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Starvation",
      "slug": "starvation",
      "type": "Noun",
      "concepts": [
        "Resource"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "State",
      "slug": "state",
      "type": "Noun",
      "concepts": [
        "Disposition"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Station",
      "slug": "station",
      "type": "Noun",
      "concepts": [
        "Connectivity"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Stranger",
      "slug": "stranger",
      "type": "Noun",
      "concepts": [
        "Access"
      ],
      "variants": [
        "Foreigner"
      ],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Strong",
      "slug": "strong",
      "type": "Adjective",
      "concepts": [
        "Disposition"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Subscribe",
      "slug": "subscribe",
      "type": "Verb",
      "concepts": [
        "Signaling"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Successor",
      "slug": "successor",
      "type": "Noun",
      "concepts": [
        "Hierarchy"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Summarize",
      "slug": "summarize",
      "type": "Verb",
      "concepts": [
        "Partiality"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Suppliers",
      "slug": "suppliers",
      "type": "Noun",
      "concepts": [
        "Resource"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Sustain",
      "slug": "sustain",
      "type": "Verb",
      "concepts": [
        "Assurance"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Tenant",
      "slug": "tenant",
      "type": "Noun",
      "concepts": [
        "Resource"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Tight",
      "slug": "tight",
      "type": "Adjective",
      "concepts": [
        "Assurance"
      ],
      "variants": [
        "Tighten"
      ],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Tighten",
      "slug": "tighten",
      "type": "Verb",
      "concepts": [
        "Assurance"
      ],
      "variants": [
        "Tight"
      ],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Trace",
      "slug": "trace",
      "type": "Verb",
      "concepts": [
        "Traceability"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Track",
      "slug": "track",
      "type": "Verb",
      "concepts": [
        "Traceability"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Tracker",
      "slug": "tracker",
      "type": "Noun",
      "concepts": [
        "Traceability"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Trail",
      "slug": "trail",
      "type": "Noun",
      "concepts": [
        "Traceability"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Transform",
      "slug": "transform",
      "type": "Verb",
      "concepts": [
        "Transformability"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Tree",
      "slug": "tree",
      "type": "Noun",
      "concepts": [
        "Hierarchy"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Unmount",
      "slug": "unmount",
      "type": "Verb",
      "concepts": [
        "Connectivity",
        "Lifecycle"
      ],
      "variants": [
        "Mount"
      ],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Update",
      "slug": "update",
      "type": "Verb",
      "concepts": [
        "Transformability"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Upgrade",
      "slug": "upgrade",
      "type": "Verb",
      "concepts": [
        "Transformability"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Validation",
      "slug": "validation",
      "type": "Noun",
      "concepts": [
        "Assurance"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Version",
      "slug": "version",
      "type": "Noun",
      "concepts": [
        "Transformability"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Violation",
      "slug": "violation",
      "type": "Noun",
      "concepts": [
        "Assurance"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Weak",
      "slug": "weak",
      "type": "Adjective",
      "concepts": [
        "Disposition"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Wire",
      "slug": "wire",
      "type": "Verb",
      "concepts": [
        "Connectivity"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Youngest",
      "slug": "youngest",
      "type": "Adjective",
      "concepts": [
        "Hierarchy"
      ],
      "variants": [
        "Oldest"
      ],
      "synonyms": [],
      "antagonists": []
    },
    {
      "word": "Zombie",
      "slug": "zombie",
      "type": "Noun",
      "concepts": [
        "Lifecycle"
      ],
      "variants": [],
      "synonyms": [],
      "antagonists": []
    }
  ]
};
